# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: mv-test 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = "mv-test"
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Valeriy Prokopchuk"]
  s.date = "2014-10-08"
  s.description = "Contains macros / matchers for database behavious testing"
  s.email = "vprokopchuk@gmail.com"
  s.files = [
    "lib/migration_validators/spec/macros/db_macros.rb",
    "lib/migration_validators/spec/matchers/db_matchers.rb",
    "lib/migration_validators/spec/support/column_wrapper.rb",
    "lib/migration_validators/spec/support/db.rb",
    "lib/migration_validators/spec/support/table_wrapper.rb",
    "lib/migration_validators/spec/support/test_adapter.rb",
    "lib/mv-test.rb"
  ]
  s.homepage = "http://github.com/vprokopchuk256/mv-test"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "2.1.10"
  s.summary = "Migration Validators project test suite"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 4.1.6"])
      s.add_runtime_dependency(%q<rspec>, [">= 3.1.0"])
      s.add_runtime_dependency(%q<rspec-its>, [">= 1.0.1"])
      s.add_development_dependency(%q<jeweler>, [">= 2.0.1"])
    else
      s.add_dependency(%q<activerecord>, [">= 4.1.6"])
      s.add_dependency(%q<rspec>, [">= 3.1.0"])
      s.add_dependency(%q<rspec-its>, [">= 1.0.1"])
      s.add_dependency(%q<jeweler>, [">= 2.0.1"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 4.1.6"])
    s.add_dependency(%q<rspec>, [">= 3.1.0"])
    s.add_dependency(%q<rspec-its>, [">= 1.0.1"])
    s.add_dependency(%q<jeweler>, [">= 2.0.1"])
  end
end

