# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mv-test}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Valeriy Prokopchuk"]
  s.date = %q{2011-03-22}
  s.description = %q{Contains macros / matchers for database behavious testing}
  s.email = %q{vprokopchuk@gmail.com}
  s.files = [
    "lib/migration_validators/spec/macros/db_macros.rb",
    "lib/migration_validators/spec/matchers/db_matchers.rb",
    "lib/migration_validators/spec/support/column_wrapper.rb",
    "lib/migration_validators/spec/support/db.rb",
    "lib/migration_validators/spec/support/table_wrapper.rb",
    "lib/migration_validators/spec/support/test_adapter.rb",
    "lib/mv-test.rb"
  ]
  s.homepage = %q{http://github.com/vprokopchuk256/mv-test}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Migration Validators project test suite}
  s.test_files = [
    "spec/migration_validators/spec/macros/db_macros_spec.rb",
    "spec/migration_validators/spec/matchers/db_matchers_spec.rb",
    "spec/migration_validators/spec/support/column_wrapper_spec.rb",
    "spec/migration_validators/spec/support/db_spec.rb",
    "spec/migration_validators/spec/support/table_wrapper_spec.rb",
    "spec/migration_validators/spec/support/test_adapter_spec.rb",
    "spec/mv-test_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activerecord>, [">= 2.3.5"])
      s.add_runtime_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<activerecord>, [">= 2.3.5"])
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<activerecord>, [">= 2.3.5"])
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

